version: '3.9'
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tips
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
  nodeapp:
    build:
      dockerfile: Dockerfile
      context: ./nodeapp
    ports:
      - "3432:3432"
    volumes:
      - /app/node_modules
      - ./nodeapp:/app
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tips 
      - NODE_PORT=3432

